### ISSUE TITLE
Named buildings

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#10]
Often addresses include named buildings--"Hotel X" or "Villa Y".  I've been using the addrLine tag to address these, but I was wondering if there is a "building title" tag in the TEI?  Or if it would be worth creating one for our next pass?

**Comment by i-davis** [comment]
Maybe relatedly, on René Daumal's (interesting!) card, the name "Princeton Bank" comes up (a check's to be deposited there). I tagged that, looking thru the TEI guidelines, as <orgName>. Then, trying to be clever, I tagged the word "Princeton" within that as <address><settlement>. Does that make any sense, or is it too much?

**Comment by cwulfman** [comment]
How about &lt;name&gt;Hotel X&lt;/name&gt;? 
Have a look at the relatively recent discussion on the TEI-L:
https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1404&L=TEI-L&D=0&1=TEI-L&9=A&I=-3&J=on&d=No+Match%3BMatch%3BMatches&z=4&P=33116

That discussion suggests something like &lt;rs type="toponym"&gt;Hotel X&lt;/rs&gt;

Ian, I think that's too much, personally. You might do that if you were encoding the sentence "She was passing through central Jersey so she deposited the check at a Princeton bank." Might be a different story if the name were "First Security Bank of Princeton" though I'm not sure how I could justify the distinction.
