### ISSUE TITLE
saur

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1058]

**Comment by clmahoney** [comment]
I found evidence of a Maurice Saur in the journals of Helene Berr, who was writing in 1942-44. So--maybe it's during that span?

**Comment by i-davis** [comment]
H. G. Well's *Experiment in Autobiography* (pub. September 1934) borrowed on a february 28. Has a subscription recorded; not mentioned in Fitch; doubt he was a friend lent to during the war (I think all the books were packed up & hidden upstairs then, right? & Sylvia was interned for the winter of 42 & spring of 43) or after the war. Going to do notBefore 1935 // notAfter 1941.
