### ISSUE TITLE
hommel

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1073]

**Comment by mnaydan** [comment]
Dates coded as 1900. Hommel not in logbooks.

**Comment by mnaydan** [comment]
Borrowed item on #s3 titled "MS (copies of)" corresp missing

**Comment by i-davis** [comment]
Eric Linklater's *Juan in America*, s3, was published 1931.

**Comment by i-davis** [comment]
I've just been through the letters dated those years, & the only mention of upstairs neighbors is in this letter from c. 1950 (Walsh 215). Given the mention of the uncle (doubt the Hommels had an uncle come visit them in Paris), & the child turning on taps, it's unlikely that this is the Hommels. Claudia Hommel was born in 1950, I think, so she wouldn't've been able to turn on faucets until after the Hommels left for Detroit in 53.

**Comment by i-davis** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/15250325/26075186/65adab6a-3982-11e7-8ffa-a2c1654bf3e3.jpg)

**Comment by i-davis** [comment]
"so as the expert can expertise it"
