### ISSUE TITLE
winger

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1080]

**Comment by mnaydan** [comment]
Couldn't find Mr. Winger in logbooks. There's a Mrs Wing in the 1921 logbook with the same ref ID #wing

**Comment by clmahoney** [comment]
I think Mary's right: these might be the same person? The card looks like it could read Mrs. Winger. And in the logbooks #wing begins in December, as does this card.

**Comment by clmahoney** [comment]
So I'm going to encode it starting in 1921. The look of the card (wide spacing) matches this earlier model.
