### ISSUE TITLE
Spouses

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mapping-expatriate-paris#11]
Is there a standard way to represent women with their husbands' names?  For example, Mrs. Thorton Baker, Mrs. James Mark Baldwin.

**Comment by cwulfman** [comment]
As far as I can tell, you would use the &lt;role&gt; element to indicate the woman's status and &lt;surname type="married"&gt;:
```xml
<persName>
           <roleName type="honorific">Mrs.</roleName>
           <surname type="married">Baldwin</surname>
</persName>
```
In the personography, I don't think I'd include the husband's forenames in her name. You could include that information in a note, or you could (as I did for Thorton Baker and James Baldwin) create &lt;person&gt; entries for the husbands and then include a listPerson element at the end:
```xml
	<listRelation>
	  <relation name="spousal" mutual="#mian.ma #mian.ar"/>
	  <relation name="spousal" mutual="#baker.th #baker.th.mrs"/>
	  <relation name="spousal" mutual="#bald.ja.mrs #bald.ja"/>
	</listRelation>
```
