### ISSUE TITLE
saillet

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1123]

**Comment by i-davis** [comment]
there's an odd column of dates which passeth understanding & which is such that, looking upon its vasty confusion, one feels that it is not to be given to one to question it

**Comment by i-davis** [comment]
no, wait - I think the odd column refers to numbers of _Life and Letters_. I'm not sure of this, however - would someone else review this - Cate, I'll tag you - & back up or not that interpretation?

**Comment by clmahoney** [comment]
Yeah that seems right to me!
