### ISSUE TITLE
aldington

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1161]

**Comment by clmahoney** [comment]
THIS IS STRANGE

**Comment by elspethgreen** [comment]
Still not updated in current scheme.

**Comment by elspethgreen** [comment]
Updated in current scheme!  Not-Before'd dates to 1928, given publication dates.  Does anyone know when Richard Adlington left Paris?  He went to America in 1942, but can't find whether he might have left Paris sooner and gone somewhere else.
