### ISSUE TITLE
"Legrand" and "Barnaud"

### ISSUE THREAD

**Issue by carlca17** [Princeton-CDH/mapping-expatriate-paris#117]
Both of these are from the "BURT" card:

It seems like Miss Burt sent books to two soldiers:
Albert Legrand (this name and address are in the personography, but in the "note" section of the Burt card)
PCR1 91e Regiment d'Infanterie
Secteur Postale 170

and

Claude Barnaud
GSSD 1 No 42 1ere Compagnie
Caserne Laharpe
Domfront, Orne

**Comment by elspethgreen** [comment]
We've decided not to include people in personography who are not in cards or logbooks
