### ISSUE TITLE
wang

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1214]

**Comment by mnaydan** [comment]
#s1 is headed "Monsieur Li Wang"; #s3 is headed "Wang Chun Jen"
These appear to be 2 different people in personography, with different addresses, but have the same refID.

**Comment by mnaydan** [comment]
#s1 has no year and is in a different hand than #s3 (dated 1934)

**Comment by elspethgreen** [comment]
These card files are not split.
