### ISSUE TITLE
Clean up existing cards so they pass schematron rules

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1223]
RSK submit list of cards that don't pass, Ellie figures out why

**Comment by rlskoeser** [comment]
@elspethgreen here's the list of files and errors I'm currently seeing in the schematron output:

- **baldwin.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **camerlynck.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
  - borrowing event cannot include more than one checkout date
- **church_mrs.tei.xml**
  - borrowing event should contain one and only one borrowed item
- **clairin.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **duff.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **hemingway.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **killen.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
  - borrowing event should contain one and only one borrowed item (x6)
  - borrowing event cannot include more than one checkout date (x3)
- **kittredge.tei.xml**
  - borrowing event should contain one and only one borrowed item (x12)
- **de_lanux.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **lamy.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **leyris.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas (x2)
- **maspero.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas (x2)
- **massey.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas (x7)
  - borrowing event should contain one and only one borrowed item (x2)
- **mesures.tei.xml**
  - borrowing event cannot include more than one checkout date 
- **pfeiffer.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **plummer.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **prenter.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **price.tei.xml*
  - borrowing event should contain one and only one borrowed item (x3)
- **raphael.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas 
  - borrowing event should contain one and only one borrowed item  (x20)
  - borrowing event cannot include more than one checkout date
- **sarraute.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **somerville.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **stein.le.tei.xml**
  - borrowing event should contain one and only one borrowed item (x2)
- **stirling.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **thellier.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas (x2)
  - borrowing event should contain one and only one borrowed item
- **theves.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas (x4)
- **de_vigan.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
  - borrowing event should contain one and only one borrowed item 
- **vogein.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas
- **waterfield.tei.xml**
   - tei:note/tei:date should not have checkedOut or returned anas (x2)
- **zibell.tei.xml**
  - tei:note/tei:date should not have checkedOut or returned anas

**Comment by elspethgreen** [comment]
Baldwin:
Looks okay--there are borrowingEvents that contain both notes and dates with #checkedOut and #returned, but I can't find such a date actually within a note.

Camerlynck:
Corrected #returned attribute on date within a note.
Found a borrowingEvent without a #returned date that is nevertheless valid (lines 486-492)
Found another borrowingEvent without a #returned date that is also valid (lines 674-676).  Edge case where return date isn't noted because we're at the bottom of the card surface.
Did NOT find a borrowingEvent with multiple dates with #checkedOut attributes.

Mrs Church
Removed #borrowedItem tag from bibl after consulting the card image.  The book title is a part of a note scrawled over the borrowingEvent, asking whether the cardholder still has the book.

Clairin:
Corrected #returned attribute on date within a note.

Maspero:
Corrected #checkedOut and #returned attributes within notes

Mesures:
Corrected second #checkedOut attribute within a borrowingEvent--was a simple mistake, should have been #returned

Pfeiffer:
Corrected #returned attribute within a note

**Comment by elspethgreen** [comment]
After a preliminary review, I feel confidant that the #returned and #checkedOut attributes within notes are simple errors--encoders are meant to delete auto-tagged dates like this, but inevitably miss some.  If there is a programmatic way to remove these attributes when they occur within notes, we should do it!

I'm working on the multiple borrowedItems per card issue now--it seems a bit more complicated, especially since the problem typically occurs on very long cards that are difficult to manually check.

**Comment by elspethgreen** [comment]
Raphael:
Multiple borrowedItem tags on line 217 was due to an incorrectly-encoded biblScope, placed within separate bibl tags rather within the same bibl as the title.  I've corrected it.
Same issue on line 257--corrected.
Line 273 has multiple corresp IDs within the borrowingEvent, but only one borrowedItem tag (correctly, as one of the books was crossed out on the card).  No correction needed.

Preliminary report on a systematic issue that causes multiple borrowedItems per borrowingEvent: incorrectly encoded biblScope tags.  When the original encoder created a separate bibl to record volume or edition information, rather than placing that information within biblScope tags within the bibl that contains title/author, this bibl was then auto-tagged as a borrowedItem.  
See line 564 for an uncorrected version.
See line 565 for biblScope encoding that was done correctly by the original encoder, and therefore correctly auto-tagged with a single #borrowedItem.
In terms of a systematic fix, the rule might be: there should never be a borrowedItem that contains ONLY biblScope information.  But this won't help place the biblScope info correctly within its bibl tag.

**Comment by rlskoeser** [comment]
@elspethgreen you said you made some corrections - would you push those to github somewhere so I can pull them into my data build branch?   I pulled an update from the latest develop versions, and you're right - baldwin doesn't have errors anymore.  I'd like to re-run the validation with all your fixes in place, and any other recent changes.

**Comment by elspethgreen** [comment]
Pushed to develop!  But to clarify--this won't solve everything, I'm still working on figuring out more systematic reasons for multiple borrowedItems.

**Comment by rlskoeser** [comment]
@elspethgreen thanks, and understood!  I hadn't realized the initial list I sent you was out of date already, and wanted to get an updated validation result.  You should be able to see the results using the travis-ci details link on #1127 (or just look at the most recent build on https://travis-ci.org/Princeton-CDH/mapping-expatriate-paris/builds )

In fact - if you want to switch to the feature/data-build branch and do your clean up there instead of in develop, then when you push changes, the build will run and you'll be able to see the updated validation results.

**Comment by elspethgreen** [comment]
Got it--will try to do that!  Can you programmatically remove the "checkedOut" and "returned" attributes within notes?  That seems like it might be easier to do all at once than by hand.

**Comment by elspethgreen** [comment]
Leo Stein-- on s10, lines 467-469, "Jacob's Room," which is crossed out on the card, was auto tagged as a borrowedItem and not untagged by an encoder.  I've corrected this.

This suggests another programmatic fix: "borrowedItem" attributes should NEVER appear within a "note" tag or within "del" tags--if one does, it is almost certainly an auto-tag that an encoder failed to untag.
