### ISSUE TITLE
groethuisen

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1257]

**Comment by ojbrowne** [comment]
Presumably having so many books on same date implies purchasing events.

**Comment by i-davis** [comment]
I don't think these're purchasing events: they have return dates. Sometimes folks got a bunch out when they were going to be out of town for a while?

**Comment by i-davis** [comment]
Found out there's a whole second card scan file, Groethuysen, which was never transcribed or encoded, presumably because of confusion with Groethuisen. I transcribed & encoded it.
