### ISSUE TITLE
wilder

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1382]

**Comment by mnaydan** [comment]
#s1 is Miss Charlotte Wilder (#wild.ch) and #s3 and #s4 are Mr. Wilder (#wild.th). If the latter is the playwright Thornton Niven Wilder, initials on top of #s3 were mistranscribed as "T.R.", I changed them to "T.N."

**Comment by mnaydan** [comment]
First level encoding did not encode dates. Logbooks confirm years of cards 1921.

**Comment by mnaydan** [comment]
A note on corresps: Solomon Eagle is author, not title. Wrote "Books in General First Series" and "Books in General Second Series." "Solomon Eagle" and "Books in General" are mis-encoded as two separate entries in borrowed titles list.
