### ISSUE TITLE
Nationality

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mapping-expatriate-paris#14]
I'd like to start adding nationality tags to the personography.  Any advice?

**Comment by cwulfman** [comment]
Have you looked at the TEI Guidelines on the subject? [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#NDPERSEpc]. I'd suggest using the key attribute to provide a formal coding and drawing those codes from 3166-1 (https://en.wikipedia.org/wiki/ISO_3166-1). E.g.,
```xml
<nationality key="fr">French</nationality>
```

**Comment by jkotin** [comment]
This is perfect.  I had seen this page, but I was thrown off by the dating -- e.g. notBefore="1966">

JK
