### ISSUE TITLE
alvear

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1418]

**Comment by i-davis** [comment]
Alvear's one of those encoded when I think Cliff was first trying to figure out a template for encoding borrowing events; the basic encoding which the comp is supposed to do (borrowing events, check out, and returned dates) wasn't done. What to do? Should I manually encode those, or can a computer do that?

**Comment by i-davis** [comment]
no, wait, never mind -

**Comment by i-davis** [comment]
alvear was a heck of a purchaser

**Comment by clmahoney** [comment]
Also some of the books don't have corresp ID's 

Works of Henry James
Muses Library
D.H. Lawrence at 30
