### ISSUE TITLE
wright

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1432]

**Comment by ojbrowne** [comment]
Lots of unknown dates and possible purchasing events

**Comment by ojbrowne** [comment]
Not sure if the insertion of borrowing events on behalf of Ellen Wright counts as a merged card ?

**Comment by i-davis** [comment]
s3 indicates that it's from 1946; it also seems more like a series of notes to self than actual borrowing events. I think Wright was only in Paris for a brief time in 46, tho he came back to France to stay in 47. So this card (s3-s4) seems a case of a famous writer being casually lent books on an informal, non-bunny basis.

**Comment by i-davis** [comment]
Borrowings of the whole Wright family up to that point, including Ellen, Richard, & Julia (their daughter), are in this file. I think it's nice to keep them all together, but like Oli, am wondering if we should.

**Comment by i-davis** [comment]
So: the following is speculative but it's the best I've got. Julia Wright was born in 42. There's a note on s7 about Richard Wright returning a book in June 52 (there's one other mention in the Wright file of a June borrowing event, but it's 20 June 1946). On Julia Wright's card, she checks out four children's books (Mother Goose, Just So Stories, &c) on a 27 June, & it looks as if she may've written the book titles herself: it's classic kid-with-a-pen handwriting. The address is in cursive & also looks like it's maybe a kid's handwriting. This is why I'm thinking maybe June 1952. If she did write it, nine to ten years old seems fairly believable for a kid's writing in cursive, being interested enough in borrowing her own books to want her own card & to write her own card. That sound credible?

**Comment by elspethgreen** [comment]
This all sounds fantastic!  Your date logic sounds right to me, so remove that tag if you've updated the dates.  Leave all the rest of the tags as is--we may want to separate out the general notes at some point.
