### ISSUE TITLE
ybarra

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1441]

**Comment by i-davis** [comment]
Ybarra's in the 1932 logbook, but the dates don't match up, & *House in Paris* (pub. 1935) was borrowed on s1.

**Comment by i-davis** [comment]
I can't figure this one out at all, other than it's post-34.

**Comment by elspethgreen** [comment]
Just do a notBefore/notAfter for 1934-1941 then!

**Comment by i-davis** [comment]
Well but wait, I don't understand, why stop at 41? 

& sorry, by post-34 I meant 35 or after. & actually, I just found another title that was first pub in 36: *The Loss of the Jane Vosper*, so it'd be 36 or after.

**Comment by i-davis** [comment]
Wait wait wait: hooray. Don't know why I didn't look in Fitch last time, but Fitch (360) says Penny Ybarra visited Paris & Sylvia in january 36, & came to a Gide reading which Fitch says took place "one cold Saturday night in February 1936" (358). Ybarra, on this card, borrows 3 books on 8 february, which was a saturday, & 1 book on 15 february, also a saturday. This seems like strong evidence for 36, so I'm going to change the dates.
