### ISSUE TITLE
tuttle

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1486]

**Comment by mnaydan** [comment]
Question about Tuttle dates: #s1 and #s2 span fall 1933- summer '34. This screenshot is from #s3 and is headed 1933, but encoded as 1934 in the xml file. I'm thinking the cards were photographed out of order? Should I change the years to 1933?

**Comment by elspethgreen** [comment]
Yes--absolutely correct the dates!  This is really helpful
