### ISSUE TITLE
Date ranges in subscription info

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#15]
I was just wondering if there is a particular way to encode a date like this:  "7 April 1934-1935."  These tend to occur in the subscription info, and implies that the subscription ends on the 7th of April, 1935.  I've encoded it as "1934-04-07" and "1935," but that doesn't seem to quite capture the information.

**Comment by jkotin** [comment]
This question relates to the personography in various ways.  Eventually, I'd like to have a field in the personography that represents when and for how long a patron used the library.

I thought I'd mention this in case it's relevant.

JK

**Comment by carlca17** [comment]
It looks like
```xml
<date from="1934-04-07" to="1935-04-07"</date>  might be the best bet.
```

I found it in the TEI guidelines here:
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONADA


The following examples demonstrate the use of the date element to mark a period of time:
```xml
<p>Those five years —
<date from="1918" to="1923">1918 to 1923</date>
 — had been, he suspected,
 somehow very important.</p>bibliography 
<p>The Eddic poems are preserved in a unique
 manuscript (Codex Regius 2365) from
<date notBefore="1250" notAfter="1300">the second half of the
   thirteenth century</date>, and <title>Hervarar
   saga</title> dates from <date when="1300">around 1300</date>.</p>bibliography 
```

**Comment by cwulfman** [comment]
Carl's right.

(Now, if one were of a perverse turn of mind, one could wonder if that range really is
```xml
 <date from="1934-04-07" to="1935-04-07">7 April 1934-1935</date>
``
or whether it refers to the nine months remaining in 1934:
```xml
<date from="1934-04-07" to="1935-01-01">7 April 1934-1935</date>
```
Does this look like it is a year's subscription from the context?
