### ISSUE TITLE
chambaz

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1529]

**Comment by i-davis** [comment]
I think this missing book id tag refers to an unclear book title at the very bottom of s1. I can't figure out the title. Looks a bit like Maitrep or Mautrep. s2 opens with a slew of Wodehouses borrowed on days soon after this unclear book, but I've been through the Wodehouse bibliography, & can't find any titles there that could possibly turn out the way this one did. Have left it as is, don't think we can sleuth this one.

**Comment by i-davis** [comment]
<img width="613" alt="screen shot 2017-05-17 at 2 06 02 pm" src="https://cloud.githubusercontent.com/assets/15250325/26169489/d65d312a-3b0b-11e7-9955-a973038659d0.png">
