### ISSUE TITLE
mespoulet

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1554]

**Comment by i-davis** [comment]
s7 missing dates. *Of Mice & Men* borrowed there, pub 1937.

Also, the address on s7 is 1 rue Dante, which is where Mespoulet is living when she first takes out a subscription in 36 or 39 (she moves in 1940, on s3, to rue de Dantzig). So we're probably talking sometime between 1937 & 1939.
