### ISSUE TITLE
violette

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1563]

**Comment by i-davis** [comment]
s5 is 1919 to 1920: the logbooks bear this out date-wise, & on 6 january 1920 there's the same extension of Violette's subscription from 3 to 6 months that's recorded middle of s5.

**Comment by i-davis** [comment]
s6 picks up where s3 leaves off

**Comment by i-davis** [comment]
Order (1919-1928):
s5,
s3,
s6,
s4,
s2,
s1,
s7,
s8
