### ISSUE TITLE
Telephone numbers?

### ISSUE THREAD

**Issue by carlca17** [Princeton-CDH/mapping-expatriate-paris#16]
What do we want to do with telephone numbers, i.e. Jasmin 29.08 (Bienenfeld)

TEI's suggestion pushes us toward a <ref target=tel:+1-555-555-5555> formation that links to American exchanges. How do we work in these old French exchanges?

**Comment by cwulfman** [comment]
Looked for prior discussions on the TEI-L and found this:

https://listserv.brown.edu/archives/cgi-bin/wa?A2=ind1209&L=TEI-L&D=0&P=37425

I think this is reasonable:
```xml
<addrLine><num @type="telephone">Jasmin 29.08</num></addrLIne>
```
Now, you could argue that the string "Jasmin 29.08" is not strictly numeric; if that bothers you, you could use a more generic referring string:

```xml
<addrLine><rs @type="telephone">Jasmin 29.08</rs></addrLIne>
```

But I think &lt;num&gt; is fine in this case.
