### ISSUE TITLE
macleish

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1621]

**Comment by mnaydan** [comment]
The Havens #s6 missing corresp

**Comment by mnaydan** [comment]
#s9 looks like Mrs A. MacLeish in header (wife's name Ada, according to Wikipedia); transcribed as Mr and tagged as Archibald on original xml doc. Should this be treated as a handwriting error on the librarian's part or is this his wife's card?

**Comment by mnaydan** [comment]
#s11 purchasing events

**Comment by elspethgreen** [comment]
I think the dates on s6 are a continuation of s3, and are indeed 1926.  S7 looks like a continuation of s5--like Beach decided she wanted to start a new card rather than continue on s5, for reasons I can't fathom.  The first book of s7 is a duplicate of the last on s5, and s7 should be 1927.

**Comment by mnaydan** [comment]
Connorfleur (#s5) missing book ID

**Comment by mnaydan** [comment]
1923-1924
        		        s1.
        			
        			1924-1925
        			s2.
        			
        			1925-1926
        			s3.
        			
        			1926
        			s6,
        			s4,
        			s5.
        			
        			1927
        			s7.
        			
        			1927-1928
        			s9,
        			s10.
        			
        			1931
        			s11.
        			
        			1933
        			s13.
        			
s8, s12, and s14 blank. s9 and s10 belong to Mrs Ada MacLeish, 1927 logbook confirms.

**Comment by mnaydan** [comment]
1923-1924
s1.
        			
1924-1925
s2.
        			
1925-1926
s3.
        			
1926
s6,
s4,
s5.
        			
1927
s7.
        			
1927-1928
s9,
s10.
        			
1931
s11.
        			
1933
s13.
        			
s8, s12, and s14 blank. s9 and s10 belong to Mrs Ada MacLeish, 1927 logbook confirms.

**Comment by mnaydan** [comment]
Years on s9 and s10 originally mistranscribed. Logbooks confirm dates span 1927-1928, fixed accordingly.
