### ISSUE TITLE
Van Den Bergh

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1709]

**Comment by i-davis** [comment]
s4 is the card of Alan Blackner, who did a short stint as a bunny from 8 august to 3 september 1935. Seems clear his quickly useless card was as quickly repurposed for Van Den Bergh.

**Comment by i-davis** [comment]
Order (1933-1936):
s6,
s1,
s2,
s5,
s3

with s4 belonging to Blackner
