### ISSUE TITLE
De Wendel

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#1710]

**Comment by i-davis** [comment]
Order (1929-1951):
s5,
s6,
s7,
s8,
s9,
s10,
s14,
s11,
s12,
s16,
s13,
s15,
s1,
s2,
s17,
s18,
s3,
s4

**Comment by i-davis** [comment]
the chronological order's pretty wonky here: seems like ordering the scans chronologically would mean separating rectos & versos (note s14 & s16). do we want to do that?
