### ISSUE TITLE
morgan

### ISSUE THREAD

**Issue by i-davis** [Princeton-CDH/mapping-expatriate-paris#188]
The Morgan file has several cards not in chronological order. Some of the cards don't have years on them, & so it's hard to tell where they fit. But one identifiable disorder is at the end, where the sequence should go: s18, s17, s16, s15, s13, s14.

**Comment by clmahoney** [comment]
1922-1925
s1,
s3,
s5,
s6

1926
s7

1934-1941
s11,
s12,
s17,
s18,
s16,
s15,
s13

Unknown but in order
s9,
s10,
s2,
s8

Blank
s4
s14
