### ISSUE TITLE
"Robert Sage" card contains borrowing info for Robert Sage and his wife

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#190]
Robert Sage:  s1, s5, s7, s9
Mrs. Robert Sage:  s3

**Comment by clmahoney** [comment]
1925-1926
          s9, 
          s8 
          
          1927
          s3 is MRS. Sage
          
          BLANK 
          s2, 
          s4, 
          s6, 
          s10
          
          Unknown
          s1 has no borrowing events and no year,
          s5, 
          s7
