### ISSUE TITLE
Different <ab> for subscription info than borrowing event info?

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#21]
Hi everyone!

In lab just now (!) we were discussing my vague recollection that Cliff advised us to keep subscription info in a separate <ab> block from the general table of books and dates.  Is this right, or was this idea scrapped in favor of simplicity on the first pass?

**Comment by cwulfman** [comment]
Without a bit more context, I can't really answer you. Let's talk about it on Wednesday.
