### ISSUE TITLE
"James Sheldon" cards out of order

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#210]

**Comment by i-davis** [comment]
tricky one: only one card is out of order by date: the order should be changed to:
s3,
s1,
s2,
s4,
sides 5, 6, 7, 8

however, as you can maybe see, this means splitting up the recto & verso of a card (s3 splits from s4)

What happened seems to be: s3 was the first card (19 september 1928 - 31 december 1928). Then they were about to use s4 to pick up where s3 left off, but Sheldon stopped coming. When Sheldon came back, they started a whole new card for him (s1 & s2). Then when they ran out of space on s2, they crossed out the one borrowing event on s4, to use the rest of that card.

Do we want to split up a recto & verso on the website?

(Let me know if this description needs clarification!)
