### ISSUE TITLE
assistants

### ISSUE THREAD

**Issue by i-davis** [Princeton-CDH/mapping-expatriate-paris#22]
the subject of S & Co's assistants came up in our lab today; if it's ever helpful for any reason, there's this page from SB's memoir:

![assistants](https://cloud.githubusercontent.com/assets/15250325/10794997/01ee5240-7d6e-11e5-87e9-23526732c910.jpg)

**Comment by cwulfman** [comment]
I've copied this into the wiki; I'm going to close this issue.
