### ISSUE TITLE
Bibl author question

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#23]
I've run across many titles like "Auden's Poems" or "Emily Dickinson's Poems," and it's hard to determine whether this is the "title' of an edition of these poems or the card-writer's way of telling apart many books named "Poems."  I've been tagging these whole strings as "titles," but have considered tagging "Poems" as "title" and the author as "author."  Does anyone have a system for this?

**Comment by cwulfman** [comment]
Good question. At the very least, do this:

```xml
<bibl>Auden's Poems</bibl>
```

but consider adding

```xml
<bibl><persName>Auden</persName>'s Poems</bibl>
```
