### ISSUE TITLE
Stein card issues

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#256]
s7-s16 are for Leo Stein, who is not in the personography

s1-s6 are for Gertrude Stein, but there are no years for any of the dates.  I've encoded as 1900 per new convention.

**Comment by elspethgreen** [comment]
These have now been separated--both have unknown dates.

**Comment by clmahoney** [comment]
Leo Stein has dates

**Comment by clmahoney** [comment]
Just added Gertrude Stein dates: s1-s4 are in order from 1920-22, but s5 seems to be much later: she's in the logbooks for 1927 so I went with that.

**Comment by clmahoney** [comment]
These two are still combined in the card, though.
