### ISSUE TITLE
"Mr Sheldon Durham"

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mapping-expatriate-paris#257]
Mr Sheldon Durham located in S3 of Ottensooser card, but he's not in the personography. 

Also it's kind of a saucy reference. And by saucy I mean kind of cute, kind of suggestive: 
"Mr Sheldon Durham came to buy Ulysses
and to inquire after Miss Ottensooser."

**Comment by elspethgreen** [comment]
We've decided not to include people in personography who are not in cards or logbooks.

Although yes that's awesome!!
