### ISSUE TITLE
Killen card file

### ISSUE THREAD

**Issue by i-davis** [Princeton-CDH/mapping-expatriate-paris#271]
This'll function as my open issue for all the sides that have no year & are thus marked 1900.

s4
s41 - just at the very bottom of the card, the aprils

**Comment by clmahoney** [comment]
Nov 1922 - Jan 1928
          s1, 
          s2, 
          s43, 
          s44, 
          s4, 
          s3, 
          s6, 
          s5, 
          s9, 
          s10, 
          s7, 
          s8, 
          s19. 
          
          June 1928 - Jan 1930
          s15, 
          s16, 
          s17, 
          s18, 
          s12, 
          s14, 
          s11. 
          
          June 1930 - October 1932
          s20, 
          s21, 
          s22, 
          s23, 
          s24, 
          s25, 
          s27, 
          s28. 
          
          August 1933 - April 1940 
          s42, 
          s41, 
          s40, 
          s39, 
          s31, 
          s32, 
          s33, 
          s34, 
          s35, 
          s36, 
          s37, 
          s38, 
          s30, 
          s29, 
          s45, 
          s46, 
          s47, 
          s48, 
          s52, 
          s51, 
          s49, 
          s50, 
          s53.
