### ISSUE TITLE
Colens - Cards out of Order

### ISSUE THREAD

**Issue by carlca17** [Princeton-CDH/mapping-expatriate-paris#275]

**Comment by i-davis** [comment]
Colens is also really strangely tabbed.

**Comment by i-davis** [comment]
s11 records the magazines borrowed for the summer of 34
s12 records the books borrowed for the summer of 34
(their dates overlap)

**Comment by i-davis** [comment]
Order (1928-1940):
                        s1,
                        s4,
                        s2,
                        s3,
                        s5,
                        s6,
                        s7,
                        s8,
                        s10,
                        s9,
                        s13,
                        s14,
                        s11,
                        s12,
                        s15,
                        s16,
                        s18,
                        s17,
                        s20,
                        s19,
                        s22,
                        s21

**Comment by elspethgreen** [comment]
I took a look at the Colens code--It is a little weird-looking, but I don't think it's worth the effort of reformatting!  It's all the same to the computer.
