### ISSUE TITLE
No years for S3 of Pottecher card

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mapping-expatriate-paris#284]
And the dates don't follow the order of S1 and S2, so I'm putting 1900 as the year.

**Comment by i-davis** [comment]
Order (1921-1925):
s3,
s4,
s1,
s2

**Comment by i-davis** [comment]
/Users/ian/Desktop/Screen Shot 2017-04-22 at 2.44.34 PM.png

think this is a renewal note for 11 October 1921

**Comment by i-davis** [comment]
<img width="96" alt="screen shot 2017-04-22 at 2 44 34 pm" src="https://cloud.githubusercontent.com/assets/15250325/25307179/6b0103fc-276a-11e7-8d18-160e1d4e51cc.png">
