### ISSUE TITLE
A couple of new faces in the Price cards, which are out of order.

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mapping-expatriate-paris#296]
S3: "Mr Cooke" mentioned; not in personography

S5: "COFFEY" crossed out at bottom of card; not in personography. 

S6: "BRODY, Miss Rachel" crossed out at bottom of card; not in personography.

**Comment by i-davis** [comment]
Order:
          s5,
          s6,
          s1,
          s2,
          s7,
          s8
         
          s3 and s4 belong to Cooke
