### ISSUE TITLE
Mostly no years for Renoir

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mapping-expatriate-paris#322]
There is a clear year for S1 and S2 is blank, but the cards are out of order so it's hard to tell what years are S3, S4, S5, and S6 so I put 1900.

**Comment by ojbrowne** [comment]
<change who="#oliverbrowne">
                1922 
                s3,
                1922-4 
                s4,
                1925-6 
                s5, 
                1926-1928
                s6,
                1928
                s1,
                s2.
            </change>
