### ISSUE TITLE
Sort of no year for Reynolds

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mapping-expatriate-paris#327]
I think PERHAPS the cards are out of order. There is only a clear year for S2, not S1 or S3.

**Comment by i-davis** [comment]
There are subscription renewals on all the cards that indicate the years; they're not out of order, I think, but rather go with small interruptions from october 1926 to november 1928. Fixed all the unknown dates; will pull request to out-of-order branch.
