### ISSUE TITLE
Birth, Married

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mapping-expatriate-paris#33]
I began to add/differentiate birth and married names in the personography.  Is it fair to assume that I don't have to change <surname>Hemingway</surname> to <surname type="birth">Hemingway</surname>  -- because  <surname>Hemingway</surname> implies that that Hemingway is Hemingway's only name?

**Comment by cwulfman** [comment]
Yes -- we can assume that by default: a name without qualifying attributes is the name we should use.
