### ISSUE TITLE
Raphael cards - sort of out of order; missing dates

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mapping-expatriate-paris#335]
There are 34 Raphael cards; the beginning few seem to be out of order. Here's a list of what dates I know and what dates I'm guessing (although if I had to guess, I put 1900 when encoding). 

S1 - 1926
S2 - 1926
S3 - possibly starting Dec. 1924 into 1925
S4 - possibly 1925 into 1926
S5 - not sure; maybe 1923-24
S6 - no year
S7 - possibly 1927
S8 - 1927
S9 - not sure but possibly 1927-28
S10 - possibly 1928-29
S11 - no idea
S12 - no year (maybe 1929)
S13 - no year (maybe 1929)
S14 - no year (maybe 1929) 
S15 - 1930
S16 - 1930-31
S17 - 1931
S18 - 1931-32
S19 - not sure ; says until 1933 so maybe 1932-33
S20 - maybe 1932
S21 - maybe 1933 or 1934
S22 - 1934
S23 - 1934-35
S24 - 1935
S25 - 1936
S26 - 1936-37
S27 - 1937
S28 - 1937-38
S29 - 1938 
S30 - 1938-39
S31 - 1939
S32 - 1939-40
S33 - 1940-41
S34 - 1941

**Comment by i-davis** [comment]
Most of Cate's & Ellie's dates here seem right to me, with a couple exceptions, which I have no doubts about & so just changed, hope that's okay. s9 & s10, the only two which were notBefored // notAftered, fit the subscription record in the logbook for 1922, & so go from 1921 to 1923. There are no more unknown dates, & the cards go mostly consecutive over the years, with I think the only real gap between s23 & s25. Here's the order:

s9,
s10,
S5,
S6,
S3,
S4,
S1,
S2,
S7,
S8,
S11,
S12,
S13,
S14,
S15,
S16,
S17,
S18,
S20,
S19,
S22,
S21,
S24,
S23,
S25,
S26,
S27,
S28,
S29,
S30,
S31,
S32,
S33,
S34,
