### ISSUE TITLE
Rivoallan - Cards out of Order

### ISSUE THREAD

**Issue by carlca17** [Princeton-CDH/mapping-expatriate-paris#337]
s7 and s8 are from 1924, the earlier cards are from the 30s

**Comment by ojbrowne** [comment]
1924-26
        s7,
        1926-9
        s8,
        1929-30
        s1,
        1931-2
        s2,
        1937-8
        s5,
        s6.
        
        S3 and S4 aren't from a proper borrowing card. Totting up credit owed on S3, S4 blank.
