### ISSUE TITLE
Benjamin

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mapping-expatriate-paris#35]
I spoke to a historian and she recommended that we mark Benjamin as "stateless."  Is there a standard TEI marker for that?  I couldn't find it.  Ideally, we would mark stateless and incorporate CW's suggestion, <nationality to="1935-09-15" key="DE">.

**Comment by cwulfman** [comment]
According to Wikipedia's summary of the ISO_3166-1 standard, (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3),
> XXA is used to represent a stateless person, as defined in Article 1 of the 1954 Convention Relating to the Status of Stateless Persons

So how about
```xml
<person>
     <faith>Jewish</faith>
      <nationality to="1935-09-15" key="DE"/>
        <note>Benjamin was born in Germany and was, under German law, a citizen of Germany
                      until the Reich Citizenship Law went into effect on September 15, 1934</note>
       </nationality>
     <nationality after="1935-09-15" key="XXA">
</person>
