### ISSUE TITLE
New Person: Mrs. K. Coyle

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mapping-expatriate-paris#39]
Created a new id & entry for the wife of Kestrel Coyle -- he card was included in the same file as her husband's.  Her id is "coyl"

**Comment by cwulfman** [comment]
Good to know! Just for future reference: do we want to make issues out of announcements like this, or is it enough for you to note it in the "commit" message when you commit the personography.tei.xml file?

**Comment by jkotin** [comment]
I am happy to make all these changes in the personography and note it in the commit message -- and leave it at that.  I'm collecting the revisions posted by Ian, Carl, et al.

My question: do we need to do anything to the card image database to separate out the cards?  I.e. do we need or want to make separate files for Mrs. Coyle and Mr. Coyle?

Another question: I haven't been revising the ids, even when I discover a first name not on the cards.  Is this right?

Last question: when I post these questions/issues, do they go to everyone involved in the project?

JK

**Comment by cwulfman** [comment]
At our meeting earlier this week, we agreed to create a ticket (issue) when we encounter multiple subscribers merged onto one card and use GitHub's labeling feature to mark those issues as "two people merged on one card for later." You can add a label to an issue by clicking on the "Labels" icon towards the upper righthand corner of the window and from the popup menu selecting one or more labels to apply to the current issue.
I'm going to close this issue and open a new one about revising IDs; that's a separate discussion, I think.
