### ISSUE TITLE
How do we deal with Volume # or Issue # of a book/magazine?

### ISSUE THREAD

**Issue by carlca17** [Princeton-CDH/mapping-expatriate-paris#4]
Building a BIBL, I've been including the issue or volume number within the BIBL, but not the title. Is there a better way to do this, a better way to capture that information?

**Comment by cwulfman** [comment]
&lt;bibl&gt; is a "mixed-content" element, which means it can contain both text and other elements. So you can usually capture issue and volume info within the bibl as simple text.  E.g.,

```xml
  <bibl>issues one and two of <title>Broom</title></bibl>
```
Can you show us an example of what you've been doing?

**Comment by carlca17** [comment]
so, I just discovered the element <biblscope>, which have as its attributes "page number," "volume," "issue:"
```xml 
<biblScope>pp 12–34</biblScope>
<biblScope unit="page" from="12" to="34"/>
<biblScope unit="volume">II</biblScope>
<biblScope unit="page">12</biblScope>
```
This would be internal to a <bibl>, obviously. Could be useful...

**Comment by cwulfman** [comment]
So, 
```xml
<bibl><biblScope unit="volume" from="1" to="2">Volumes 1 and 2</biblScope> of <title>Broom</title></bibl>
```
Not sure this level of detail is necessary for this pass, though.  Thoughts, everyone?

**Comment by jdmccart** [comment]
I agree that we don't need volume # entries for book's or magazines --- that can get scooped up on a later pass.
________________________________
