### ISSUE TITLE
pseudonyms

### ISSUE THREAD

**Issue by cwulfman** [Princeton-CDH/mapping-expatriate-paris#5]
JK asks:
We list Bryher in the personography like this:
```xml
<person xml:id="elle.an">
<idno type="viaf">111923629</idno>
<persName>
<surname>Ellerman</surname>
<forename>Anne Winifred</forename>
</persName>
<note>Bryher is Pseudonym for Anne Winifred Ellerman</note>
</person>
```
Is this right?  Should we list her name as Bryher?  Or create separate tag for a pseudonym?

**Comment by cwulfman** [comment]
The TEI has us covered here: [http://wiki.tei-c.org/index.php/Prosopography#Pseudonyms]
So:

```xml
<person xml:id="elle.an">
<idno type="viaf">111923629</idno>
<persName>
<surname>Ellerman</surname>
<forename>Anne</forename>
<forename>Winifred</forename>
</persName>
<persName type="pseudo">
<forename>Anne</forename>
<forename>Winifred</forename>
<surname>Bryher</surname>
</persName>
</person>
```

**Comment by jkotin** [comment]
Thank you.

This is what the Bryher entry looks like now:

<person xml:id="elle.an">
<idno type="viaf">111923629</idno>
<persName>
<surname>Ellerman</surname>
<forename>Anne</forename>
<forename>Winifred</forename>
</persName>
<persName type="pseudo">Bryher</persName>
<birth>1894</birth>
<death>1983</death>
<sex value="2"/>
</person>

I didn't use this more complicated tag:

<persName type="pseudo" sort="1">Bryher</persName>

Does this all look right to you?

JK

**Comment by cwulfman** [comment]
No — it would be better if you copy-pasted the forenames as I showed you.
