### ISSUE TITLE
split names?

### ISSUE THREAD

**Issue by cwulfman** [Princeton-CDH/mapping-expatriate-paris#6]
JK asks:

When RBSC scanned the cards, sometimes they listed two patrons with the same name under a single entry.  When this happens, should I make a new listing?  For example, I think there are two people named Mlle Brull: Colette and Odile.

Thus, I've done this:
```xml
<person xml:id="brul.co">
  <persName>
	    <surname>Brull</surname>
	    <forename>Colette</forename>
  </persName>
</person>
<person xml:id="brul.od">
     	<persName>
     		<surname>Brull</surname>
     		<forename>Odile</forename>
     	</persName>
</person>
```
Is this the right thing to do?

**Comment by cwulfman** [comment]
Yes, this is the right thing to do. And whoever encodes Brull should beware of this. In fact, I'll have to fix this on the image server.

**Comment by jkotin** [comment]
Great, thank you.  There are a few more like this.  I'll let you know when I get to them.

JK

**Comment by cwulfman** [comment]
Ok. Heading off now — more in the next few days.

-C

On Oct 25, 2015, at 2:33 PM, jkotin <notifications@github.com<mailto:notifications@github.com>> wrote:

Great, thank you. There are a few more like this. I'll let you know when I get to them.

JK

**Comment by carlca17** [comment]
Josh--I have a whole list from the transcription phase of issues (mostly later in the alphabet) of card files that include multiple card holders under the same name, misplaced cards, etc.

Two questions:
1. Should we create a central location where we share these issues with one another, under the "wiki" here, perhaps? A place where we can all keep track of this together, and which Cliff can reference for fixes that need to happen on the image server?
2. On the file/version management side: my inclination is to let the personography file be your baby: that we would report issues to you, and you make the changes in that file. Or do you want us to be continually updating it as we find things?

**Comment by jkotin** [comment]
Thanks Carl --

Answers below.

> Two questions:

> 1. Should we create a central location where we share these issues with one another, under the "wiki" here, perhaps? A place where we can all keep track of this together, and which Cliff can reference for fixes that need to happen on the image server?

Yes, this is a good idea.  Cliff would you set this up the way you think best?

> 2. On the file/version management side: my inclination is to let the personography file be your baby: that we would report issues to you, and you make the changes in that file. Or do you want us to be continually updating it as we find things?

I agree.

**Comment by elspethgreen** [comment]
I started a page on the wiki called "Card Issue Repository" with a few preliminary categories of issues.  Would something like this work?
