### ISSUE TITLE
Mrs. Le Colleter

### ISSUE THREAD

**Issue by carlca17** [Princeton-CDH/mapping-expatriate-paris#66]
At the bottom of BLAESS #s3, there's a reference to a "Mrs. Le Colleter;" Blaess lent a book to her. Not finding her in the personography. Pretty sure on spelling, but possible variants could be "Le Coeleter" or "Le Couleter."

**Comment by elspethgreen** [comment]
We've decided not to include people in personography who are not in cards or logbooks
