### ISSUE TITLE
Brull directory in the image directory is actually two people

### ISSUE THREAD

**Issue by cwulfman** [Princeton-CDH/mapping-expatriate-paris#7]
The directory needs to be split into two (probably brullc and brullo), and the encoder for Brull needs to create two TEI files.

**Comment by carlca17** [comment]
I'm now transcribing the Boyd card and wondering if we have a protocol for creating new TEI files. Do I leave the encoded transcriptions of all cards in the both files and simply change the header to refer to the Madeleine, not James Boyd?? If I am delineating the cards that belong to each, what else do I need to divide to be sure that only the card images assigned to each TEI file appear?

Should I split the "facsimile" "surfaces" so they reflect only the cards included in the final file? 
(i.e. [#s1 - s2] ==> James / [#s3 - s4] ==> Madeleine)
