### ISSUE TITLE
harper

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#853]

**Comment by mnaydan** [comment]
This is an overdue notice (Shakespeare pulling out his hair) for a single book borrowed 8 June 1933. Should I encode it as a borrowing event without a return date?

**Comment by elspethgreen** [comment]
Sorry, I just noticed this question!  I remember this card--since it's not a normal library card, I'd flag it as a "bug" and not encode any borrowing events.
