### ISSUE TITLE
treirse

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mapping-expatriate-paris#866]

**Comment by i-davis** [comment]
there's a book on here called *interpreter of dreams*, which was logged in the borrowing events file as the actual title; any chance we should just go ahead & guess that's meant to be *interpretation of dreams*, & redo its corresp accordingly?

**Comment by elspethgreen** [comment]
Ian--from now on, if you notice a problem with corresp, tag it with
"Missing ID" so it goes in the pool to deal with later.

LOL-ing at your comments
